apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xkwst0p6a-nodejs 
  janus-idp.io/tekton: xkwst0p6a-nodejs
  backstage.io/kubernetes-id: xkwst0p6a-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xkwst0p6a-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  